apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: suricatas.edcop.io
spec:
  group: edcop.io
  names:
    kind: Suricata
    listKind: SuricataList
    plural: suricatas
    singular: suricata
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
